
server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: config
  mvc:
    view:
      prefix: /templates/
      suffix: .html


  jpa:
    show-sql: true